default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: weekly_workshop

development:
  <<: *default
  database: ar_migrations_dev

test:
  <<: *default
  database: ar_migrations_test

production:
  <<: *default
  database: ar_migrations_prod
